name: Terraform Apply and Destroy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy

permissions:
      id-token: write
      contents: read

jobs:
  terraform:
    name: Terraform Apply or Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975049998898:role/githubaction-assumerole
          role-session-name: github-assume
          aws-region: us-east-1
          
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        continue-on-error: true
        run: |
          tflint --init
          tflint --recursive
      
      # Install Checkov.
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      # Run Checkov to scan Terraform files.
      - name: Run Checkov Scan
        run: |
          checkov -d .    # Scan the current directory for Terraform files.
      
      - name: Check if Checkov output file exists
        run: |
          if [ -f checkov_output.txt ]; then
            echo "Checkov output found!"
          else
            echo "Checkov output not found!"
            exit 1
          fi
          
      # Optional: Upload Checkov results to GitHub.
    #  - name: Upload Checkov results to GitHub
    #    uses: actions/upload-artifact@v3
    #    with:
    #      name: checkov-results
    #      path: checkov_output.txt

      # Optional: Fail the workflow if Checkov finds issues.
      - name: Fail if Checkov finds issues
        run: |
          if grep -q "Failed" checkov_output.txt; then
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate 
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: terraform apply -auto-approve 

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve 
