name: Terraform Apply and Destroy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy

permissions:
      id-token: write
      contents: write

jobs:
  terraform:
    name: Terraform Apply or Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975049998898:role/githubaction-assumerole
          role-session-name: github-assume
          aws-region: us-east-1
          
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        continue-on-error: true
        run: |
          tflint --init
          tflint --recursive
      
      # Install Checkov.
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      # Run Checkov to scan Terraform files.
      - name: Run Checkov Scan
        continue-on-error: true
        run: |
          checkov -d ./ --skip-path .github/* --soft-fail    # Scan the current directory for Terraform files.

#      - name: Install terraform-docs
#        run: |
#          curl -sSLo terraform-docs.tar.gz https://terraform-docs.io/dl/v0.20.0/terraform-docs-v0.20.0-linux-amd64.tar.gz
#          tar -xzf terraform-docs.tar.gz
#          chmod +x terraform-docs
#          sudo mv terraform-docs /usr/local/bin/
# 
# 
#      - name: Generate Terraform Docs
#        run: |
#          terraform-docs markdown table . > README.md
#      
#      - name: Commit and push changes
#        run: |
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git add README.md
#          git commit -m "Update Terraform docs [skip ci]" || echo "No changes to commit"
#          git push 

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform validate 
        run: terraform validate

      - name: Run Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Generate Terraform Plan Output
        run: terraform show -no-color tfplan > plan.txt

      - name: Install terraform-docs
        run: |
          curl -sSL https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz | tar xz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Terraform Documentation
        run: terraform-docs markdown . > README.md

      - name: Commit and Push Documentation (if needed)
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'Terraform Bot'
          author_email: 'terraform@bot.com'
          message: 'Update README.md with Terraform docs'

      - name: Post Terraform Plan as PR comment
        uses: peter-evans/comment-pr@v3  # Use the latest stable version (v3)
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Terraform Plan Output
            ```plaintext
            $(cat plan.txt)
            ```
      
      

  
#      - name: Terraform Plan
#        run: terraform plan 
      
#      - name: Generate Terraform Docs
#        uses: terraform-docs/gh-actions@v1.4.1
#        with:
#          working-dir: ./
#          output-file: README.md
#          output-method: inject
#          git-push: "true"

      - name: Terraform Apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: terraform apply -auto-approve 

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve 
